name: "prod"

on:
  push:
    branches:
      - 'prod'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Create Prod Yaml"
        run: |
          touch ./src/main/resources/application-prod.yml
          echo "${{ secrets.APPLICATION_PROD }}" > ./src/main/resources/application-prod.yml
          cat ./src/main/resources/application-prod.yml
      - name: "Set up JDK 17"
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: "Grant execute permission for gradlew"
        run: chmod +x gradlew
      - name: "Build with Gradle"
        run: ./gradlew clean buildZip
      - name: "Deliver to AWS S3"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws s3 cp --region ap-northeast-2 --acl private ./build/distributions/{{project_name_camel_upper_case}}-0.0.1-SNAPSHOT.zip s3://carmore-lambda-repository
      - name: "Update lambda"
        uses: rotarydialer/update-lambda-s3@main
        env:
          LAMBDA_NAME: {{project_name_camel_upper_case}}
          AWS_S3_BUCKET: carmore-lambda-repository
          AWS_S3_KEY: {{project_name_camel_upper_case}}-0.0.1-SNAPSHOT.zip
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
